### PR TITLE
Bump Android Studio 4.2

### PR DESCRIPTION
**Pull request by hannesa2**
With most recent 4.2 I can't build repo

### CODE REVIEW

**Comment by hannesa2** [comment]
@space-pope Github introduced something new, now it's your task to make CI work 

image

**Review by space-pope — APPROVED** [review]
Thank you for not taking it all the way to the recommendation made by the latest canary (AGP 7.0), which breaks builds on older canaries. This at least maintains some backwards compatibility, so I'm fine with it.

**Comment by hannesa2** [comment]
> Thank you for not taking it all the way to the recommendation made by the latest canary (AGP 7.0), which breaks builds on older canaries. This at least maintains some backwards compatibility, so I'm fine with it.

But it's not very smart not using Android Studio Artic Fox. This repo doesn't work on Emulator, and when you don't want to use a cable, you need Artic Fox

image

**Comment by space-pope** [comment]
If it were a question of merely _supporting_ Arctic Fox, I would agree. Unfortunately, it's a binary choice—if I switch to AGP 7.0 in the repository, it _forces_ users to have Arctic Fox in order to run the code (or manually downgrade the AGP). Arctic Fox is not considered a stable build, and as you've already noted, the microphone may work there, but Android's `SpeechRecognizer` does not. Especially now that 4.2 has made it to RC, I don't want to force people onto preview builds if I don't have to.

**Pull request merged**
